apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  generation: 2
  labels:
    app: sso
  name: my-keycloak
  namespace: keycloak
spec:
  hostname:
    hostname: ${KEYCLOAK_SERVER} 
  http:
    tlsSecret: keycloak-tls-secret
  instances: 1
