apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - mappingMethod: claim
    name: keycloak
    openID:
      ca:
        name: openid-ca-keycloak
      claims:
        email:
        - email
        name:
        - name
        preferredUsername:
        - preferred_username
      clientID: ${KEYCLOAK_OIDC_CLIENT_ID}
      clientSecret:
        name: openid-client-secret-keycloak
      extraScopes: []
      issuer: https://${KEYCLOAK_SERVER}/realms/${KEYCLOAK_REALM_NAME}
    type: OpenID
