apiVersion: v1
kind: Secret
metadata:
  name: access-key
  namespace: default
stringData:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
---
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: model-data
  namespace: default
spec:
  mounts:
  - mountPoint: "s3://zj-models/models/"
    name: models
    path: /models
    options:
      # alluxio.underfs.s3.endpoint: s3.amazonaws.com
      alluxio.underfs.s3.region: "us-east-1"
      alluxio.underfs.s3.secure.http.enabled: "true"
    encryptOptions:
      - name: s3a.accessKeyId
        valueFrom:
          secretKeyRef:
            name: access-key
            key: AWS_ACCESS_KEY_ID
      - name: s3a.secretKey
        valueFrom:
          secretKeyRef:
            name: access-key
            key: AWS_SECRET_ACCESS_KEY
  accessModes:
    - ReadOnlyMany

---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: model-data
  namespace: default
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 10Gi
        high: "0.99"
        low: "0.99"
