apiVersion: v1
kind: Secret
metadata:
  name: access-key
  namespace: default
stringData:
  aws.accessKeyId: ${AWS_ACCESS_KEY_ID}
  aws.secretKey: ${AWS_SECRET_ACCESS_KEY}
---
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: model-data
  namespace: default
spec:
  mounts:
  - mountPoint: "s3://zj-models"
    name: models
    path: /
    options:
      alluxio.underfs.s3.region: us-east-1
      alluxio.underfs.s3.endpoint: s3.amazonaws.com
    encryptOptions:
      - name: aws.accessKeyId
        valueFrom:
          secretKeyRef:
            name: access-key
            key: aws.accessKeyId
      - name: aws.secretKey
        valueFrom:
          secretKeyRef:
            name: access-key
            key: aws.secretKey
  # accessModes:
  #   - ReadOnlyMany

---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: model-data
  namespace: default
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 10Gi
        high: "0.99"
        low: "0.99"
