apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-qwen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-qwen
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: s3-qwen
    spec:
      containers:
      - name: qwen
        args:
        - |
          echo "check /mnt/s3 folder"
          ls -la /mnt/s3
          rm -rf /mnt/s3/*
          echo "start to mount s3 bucket, date: $(date)"
          s3fs zj-models /mnt/s3/ -o allow_other -o use_cache=/tmp
          echo "start to check s3fs mount"
          while true; do
            echo "s3fs mount is not ready, waiting ..."
            mount | grep s3fs
            sleep 1
            if [ "$(mount | grep -c s3fs)" -ne 0 ]; then
              echo "s3fs is ready" && break
            fi
          done
          echo "check /mnt/s3 folder"
          ls -la /mnt/s3
          exec python3 -m vllm.entrypoints.openai.api_server --trust-remote-code \
            --model /mnt/s3/models/Qwen1.5-4B-Chat --gpu-memory-utilization 0.95 --max-model-len 8192 \
            --dtype half --enforce-eager
        command: ["/bin/sh", "-c"]
        image: quay.io/zhujian/s3fs:vllm
        securityContext:
          privileged: true
        env:
        - name: AWSACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: access-key
              key: AWS_ACCESS_KEY_ID
        - name: AWSSECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: access-key
              key: AWS_SECRET_ACCESS_KEY
        # volumeMounts:
        # - name: s3-mount
        #   mountPath: /mnt/s3
        #   mountPropagation: Bidirectional
        ports:
        - containerPort: 8000
          name: qwen
        readinessProbe:
          httpGet:
            path: /v1/models
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /v1/models
            port: 8000
          initialDelaySeconds: 120 
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: 16Gi
          requests:
            nvidia.com/gpu: "1"
            memory: 2Gi
        volumeMounts:
        - name: s3-mount
          mountPath: /mnt/s3
          # subPath: models/Qwen1.5-4B-Chat
          # mountPropagation: HostToContainer
          mountPropagation: Bidirectional
      volumes:
      - name: s3-mount
        hostPath:
          path: "/tmp/s3-2"
          type: DirectoryOrCreate
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
