apiVersion: v1
kind: Secret
metadata:
  name: access-key
  namespace: default
stringData:
  fs.oss.accessKeyId: ${OSS_ACCESS_KEY}
  fs.oss.accessKeySecret: ${OSS_SECRET_KEY}
---
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: model-data
  namespace: default
spec:
  mounts:
  - mountPoint: "oss://mybucket/models/"
    name: models
    path: /
    options:
      fs.oss.endpoint: oss-cn-beijing-internal.aliyuncs.com
    encryptOptions:
      - name: fs.oss.accessKeyId
        valueFrom:
          secretKeyRef:
            name: access-key
            key: fs.oss.accessKeyId
      - name: fs.oss.accessKeySecret
        valueFrom:
          secretKeyRef:
            name: access-key
            key: fs.oss.accessKeySecret
  accessModes:
    - ReadOnlyMany
---
apiVersion: data.fluid.io/v1alpha1
kind: JindoRuntime
metadata:
  name: model-data
  namespace: default
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 30Gi
        high: "0.99"
        low: "0.99"
  fuse:
    properties:
      fs.oss.download.thread.concurrency: "200"
      fs.oss.read.buffer.size: "8388608" # 8M
      fs.oss.read.readahead.max.buffer.count: "200"
      fs.oss.read.sequence.ambiguity.range: "2147483647"
