kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:resource-usage-collect:agent
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes","configmaps", "pods", "events" ]
    verbs: [ "get", "list", "watch", "create", "update", "delete","deletecollection", "patch" ]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "create", "get", "list", "update", "watch", "patch" ]
  - apiGroups: [ "cluster.open-cluster-management.io" ]
    resources: [ "addonplacementscores" ]
    verbs: [ "get", "list", "watch", "create", "update", "delete","deletecollection", "patch" ]
  - apiGroups: [ "cluster.open-cluster-management.io" ]
    resources: [ "addonplacementscores/status" ]
    verbs: [ "update", "patch" ]
  - apiGroups: [ "config.openshift.io" ]
    resources: [ "infrastructures" ]
    verbs: [ "get", "list", "watch" ]
