apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management-addon-manager-resource-usage-collect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:resource-usage-collect:agent
subjects:
  - kind: ServiceAccount
    name: addon-manager-controller-sa
    namespace: open-cluster-management-hub
