apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:spire-v1
  namespace: spire
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:spire-v1
subjects:
- kind: ServiceAccount
  name: spire-server
  namespace: spire
- kind: ServiceAccount
  name: spire-agent
  namespace: spire
